name: "Terraform Plan"
on: [pull_request]

# this version is more secure, as it does not risk leaking information from TFE
# however, assuming your secrets are properly marked sensitive, it should not be necessary.
# https://github.com/hashicorp/tfc-workflows-github/blob/main/workflows/terraform-cloud.speculative-run.workflow.yml

env:
  TF_WORKSPACE: "$TF_WORKSPACE"
  TF_CLOUD_ORGANIZATION: "$TF_CLOUD_ORGANIZATION"
  TF_CLOUD_HOSTNAME: "$TF_CLOUD_HOSTNAME"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          hostname: ${{ env.TF_CLOUD_HOSTNAME }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative_run: true

      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          hostname: ${{ env.TF_CLOUD_HOSTNAME }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: true

      - uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        id: plan-output
        with:
          plan: ${{ steps.run.outputs.plan_id }}

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Cloud Plan Output')
            })
            const output = `#### Terraform Cloud Plan Output
               \`\`\`\n
               Plan: ${{ steps.plan-output.outputs.add }} to add, ${{ steps.plan-output.outputs.change }} to change, ${{ steps.plan-output.outputs.destroy }} to destroy.
               \`\`\`
               [Terraform Cloud Plan](${{ steps.run.outputs.run_link }})
               `
            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
